# _config.yml
title: "Data Insights & Economics"
description: "Portfolio of a Business Analyst specializing in Python, Tableau, and Economic Modeling."
theme: jekyll-theme-minimal

# ⚠️ 关键修复：告诉 Jekyll 你的仓库名是什么
baseurl: "/about"
url: "https://learnedsd.github.io"

# 其它设置
plugins:
  - jekyll-seo-tag
